"""parties, members, invites

Revision ID: 45f50c1a62c5
Revises: 90dd3d1df113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f50c1a62c5'
down_revision = '90dd3d1df113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.String(length=22), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('topic', sa.String(length=20), nullable=False),
    sa.Column('host_user_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=20), server_default=sa.text("'lobby'"), nullable=False),
    sa.Column('option_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('member_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('submitted_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('center_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('center_lon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('radius_m', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('swipe_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('lobby', 'swiping', 'complete', 'cancelled', 'expired')", name='ck_parties_state'),
    sa.CheckConstraint("topic IN ('restaurant', 'movie', 'activity')", name='ck_parties_topic'),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.create_index('ix_parties_host_user_id', ['host_user_id'], unique=False)
        batch_op.create_index('ix_parties_state_deadline', ['state', 'swipe_deadline_at'], unique=False)

    op.create_table('invites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('party_id', sa.BigInteger(), nullable=False),
    sa.Column('code_hmac', sa.LargeBinary(length=32), nullable=False),
    sa.Column('code_prefix', sa.String(length=2), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hmac')
    )
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.create_index('uq_invites_one_live_per_party', ['party_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))

    op.create_table('party_members',
    sa.Column('party_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=10), server_default=sa.text("'member'"), nullable=False),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'active'"), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('host', 'member')", name='ck_party_members_role'),
    sa.CheckConstraint("status IN ('active', 'left', 'kicked')", name='ck_party_members_status'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('party_id', 'user_id')
    )
    with op.batch_alter_table('party_members', schema=None) as batch_op:
        batch_op.create_index('ix_party_members_user', ['user_id', 'joined_at'], unique=False)
        batch_op.create_index('uq_party_members_one_host', ['party_id'], unique=True, postgresql_where=sa.text("role = 'host' AND status = 'active'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_members', schema=None) as batch_op:
        batch_op.drop_index('uq_party_members_one_host', postgresql_where=sa.text("role = 'host' AND status = 'active'"))
        batch_op.drop_index('ix_party_members_user')

    op.drop_table('party_members')
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_index('uq_invites_one_live_per_party', postgresql_where=sa.text('revoked_at IS NULL'))

    op.drop_table('invites')
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_index('ix_parties_state_deadline')
        batch_op.drop_index('ix_parties_host_user_id')

    op.drop_table('parties')
    # ### end Alembic commands ###
